// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzcipopufvmixwqbjymt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6Y2lwb3B1ZnZtaXh3cWJqeW10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTczNDQsImV4cCI6MjA2NzczMzM0NH0.4ns-Ody17bj03Udg_xI31p8dmftOkjyFWT6QM6uID7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});